def enum_type_fix(key):

    if key not in ["AD0",
                   "AD1",
                   "AD2",
                   "AD3",
                   "AD4"]:
        key = int(key)

    return key


enums_dict = {
            0: "reference",
            1: "part",
            2: "their_reference",
            3: "title",
            4: "name",
            5: "first_name",
            6: "middle_name",
            7: "last_name",
            8: "address1",
            9: "address2",
            10: "city",
            11: "region",
            12: "country",
            13: "postal_code",
            14: "account_number",
            15: "sort_code",
            16: "special1",
            17: "special2",
            18: "special3",
            19: "special4",
            20: "passport_number",
            21: "passport_expiry",
            22: "licence_number",
            23: "licence_expiry",
            24: "staff_number",
            25: "social_security_number",
            26: "card_type",
            27: "card_number",
            28: "card_name",
            29: "card_issue_number",
            30: "card_expiry_date",
            31: "card_issue_date",
            32: "phone_number",
            33: "mobile_number",
            34: "email_address",
            35: "dob",
            36: "type",
            37: "lifetime",
            38: "style",
            39: "card",
            40: "sex",
            41: "marketing",
            42: "passport_issuer",
            43: "licence_issuer",
            44: "occupation",
            45: "marketing2",
            46: "maidenname",
            47: "building_number",
            48: "resident",
            49: "marketing3",
            50: "flat",
            51: "building_name",
            52: "address_country_code",
            53: "address_region_code",
            54: "birth_city",
            55: "birth_country_code",
            56: "birth_region_code",
            57: "nationality_country_code",
            58: "birth_nationality_country_code",
            59: "organisation",
            60: "last_name_2",
            61: "idscan",
            "AD0": "code",
            "AD1": "data1",
            "AD2": "data2",
            "AD3": "data3",
            "AD4": "data4"
            }
